run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 1m
  tests: false

linters:
  enable:
  # Default
  - govet
  - errcheck
  - staticcheck
  - unused
  - gosimple
  - structcheck
  - varcheck
  - ineffassign
  - deadcode
  - typecheck
  # Extra, see list of https://golangci-lint.run/usage/linters/
  - bodyclose
  - golint
  # - rowserrcheck is not applicable here
  - stylecheck
  - gosec
  # - interfacer is deprecated
  - unconvert
  - dupl
  - goconst
  - gocyclo
  - gocognit
  - asciicheck
  - gofmt
  - goimports
  - maligned
  # - depguard is not applicable here
  - misspell
  # - lll allow long lines for now, maybe revisit this later
  - unparam
  - dogsled
  - nakedret
  - prealloc
  - scopelint
  - gocritic
  - gochecknoinits
  - gochecknoglobals
  # - godox don't error although there are TODOs in the code
  - funlen
  - whitespace
  # - wsl allow "non-idiomatic" whitespace formattings for now
  - goprintffuncname
  - gomnd
  - goerr113
  # - gomodguard is not applicable here
  - godot
  # - testpackage is not applicable here
  # - nestif is covered by gocognit
  # - exportloopref is covered by scopelint
  - exhaustive
  - nolintlint
