# permissions for end users to view clusterspecs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterspec-viewer-role
rules:
- apiGroups:
  - baremetalproviderspec
  resources:
  - clusterspecs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - baremetalproviderspec
  resources:
  - clusterspecs/status
  verbs:
  - get
