# permissions for end users to view existinginframachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: existinginframachine-viewer-role
rules:
- apiGroups:
  - cluster.weave.works
  resources:
  - existinginframachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.weave.works
  resources:
  - existinginframachines/status
  verbs:
  - get
