# permissions for end users to view existinginfraclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: existinginfracluster-viewer-role
rules:
- apiGroups:
  - cluster.weave.works
  resources:
  - existinginfraclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.weave.works
  resources:
  - existinginfraclusters/status
  verbs:
  - get
