# permissions for end users to edit existinginfraclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: existinginfracluster-editor-role
rules:
- apiGroups:
  - cluster.weave.works
  resources:
  - existinginfraclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.weave.works
  resources:
  - existinginfraclusters/status
  verbs:
  - get
