# permissions for end users to edit machinespecs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinespec-editor-role
rules:
- apiGroups:
  - baremetalproviderspec
  resources:
  - machinespecs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - baremetalproviderspec
  resources:
  - machinespecs/status
  verbs:
  - get
