# permissions for end users to view machinespecs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinespec-viewer-role
rules:
- apiGroups:
  - baremetalproviderspec
  resources:
  - machinespecs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - baremetalproviderspec
  resources:
  - machinespecs/status
  verbs:
  - get
